Chapter 22
# 利用unstack() 将长格式转换为宽格式
Book_1《编程不难》 | 鸢尾花书：从加减乘除到机器学习

In [1]:
import pandas as pd
import numpy as np

In [2]:
# 创建班级、学号和科目的所有可能组合
classes =  ['A', 'B']
student_ids = [1, 2, 3, 4]
subjects =    ['Art', 'Math', 'Science']

In [3]:
# 使用随机数生成成绩数据
length = len(classes)*len(student_ids)*len(subjects)
scores = np.random.randint(3, 6, size=(length))

In [4]:
# 创建多级索引
index = pd.MultiIndex.from_product(
    [classes, student_ids, subjects],
    names=['Class', 'Student ID', 'Subject'])

In [6]:
# 创建数据帧
df = pd.DataFrame(scores, index=index,
    columns=['Final']) #columns=['Final']将列索引命名为final
df

                          Final
Class Student ID Subject
A     1          Art          3
                 Math         4
                 Science      3
      2          Art          3
                 Math         5
                 Science      4
      3          Art          5
                 Math         5
                 Science      3
      4          Art          5
                 Math         3
                 Science      3
B     1          Art          3
                 Math         3
                 Science      5
      2          Art          5
                 Math         4
                 Science      4
      3          Art          3
                 Math         5
                 Science      4
      4          Art          5
                 Math         3
                 Science      4

In [10]:
# df.unstack(0)
df.unstack('Class')  # 将行索引作为列索引

                   Final
Class                  A  B
Student ID Subject
1          Art         3  3
           Math        4  3
           Science     3  5
2          Art         3  5
           Math        5  4
           Science     4  4
3          Art         5  3
           Math        5  5
           Science     3  4
4          Art         5  5
           Math        3  3
           Science     3  4

In [11]:
df.columns

Index(['Final'], dtype='object')

In [13]:
df.columns.names

FrozenList([None])

In [14]:
df.unstack([1,2])

           Final                                                          \
Student ID     1                2                3                4
Subject      Art Math Science Art Math Science Art Math Science Art Math
Class
A              3    4       3   3    5       4   5    5       3   5    3
B              3    3       5   5    4       4   3    5       4   5    3


Student ID
Subject    Science
Class
A                3
B                4

In [15]:
df.unstack(['Student ID','Subject'])

           Final                                                          \
Student ID     1                2                3                4
Subject      Art Math Science Art Math Science Art Math Science Art Math
Class
A              3    4       3   3    5       4   5    5       3   5    3
B              3    3       5   5    4       4   3    5       4   5    3


Student ID
Subject    Science
Class
A                3
B                4

In [16]:
df.index

MultiIndex([('A', 1,     'Art'),
            ('A', 1,    'Math'),
            ('A', 1, 'Science'),
            ('A', 2,     'Art'),
            ('A', 2,    'Math'),
            ('A', 2, 'Science'),
            ('A', 3,     'Art'),
            ('A', 3,    'Math'),
            ('A', 3, 'Science'),
            ('A', 4,     'Art'),
            ('A', 4,    'Math'),
            ('A', 4, 'Science'),
            ('B', 1,     'Art'),
            ('B', 1,    'Math'),
            ('B', 1, 'Science'),
            ('B', 2,     'Art'),
            ('B', 2,    'Math'),
            ('B', 2, 'Science'),
            ('B', 3,     'Art'),
            ('B', 3,    'Math'),
            ('B', 3, 'Science'),
            ('B', 4,     'Art'),
            ('B', 4,    'Math'),
            ('B', 4, 'Science')],
           names=['Class', 'Student ID', 'Subject'])

In [18]:
df.unstack(1)

              Final
Student ID        1  2  3  4
Class Subject
A     Art         3  3  5  5
      Math        4  5  5  3
      Science     3  4  3  3
B     Art         3  5  3  5
      Math        3  4  5  3
      Science     5  4  4  4

In [19]:
df.unstack('Student ID')

              Final
Student ID        1  2  3  4
Class Subject
A     Art         3  3  5  5
      Math        4  5  5  3
      Science     3  4  3  3
B     Art         3  5  3  5
      Math        3  4  5  3
      Science     5  4  4  4

In [20]:
print(df.unstack(2))
print(df.unstack('Subject'))

                 Final
Subject            Art Math Science
Class Student ID
A     1              3    4       3
      2              3    5       4
      3              5    5       3
      4              5    3       3
B     1              3    3       5
      2              5    4       4
      3              3    5       4
      4              5    3       4
                 Final
Subject            Art Math Science
Class Student ID
A     1              3    4       3
      2              3    5       4
      3              5    5       3
      4              5    3       3
B     1              3    3       5
      2              5    4       4
      3              3    5       4
      4              5    3       4

In [22]:
df.unstack([1,2])

           Final                                                          \
Student ID     1                2                3                4
Subject      Art Math Science Art Math Science Art Math Science Art Math
Class
A              3    4       3   3    5       4   5    5       3   5    3
B              3    3       5   5    4       4   3    5       4   5    3


Student ID
Subject    Science
Class
A                3
B                4

In [21]:
df.unstack([2,1])

           Final                                                          \
Subject      Art Math Science Art Math Science Art Math Science Art Math
Student ID     1    1       1   2    2       2   3    3       3   4    4
Class
A              3    4       3   3    5       4   5    5       3   5    3
B              3    3       5   5    4       4   3    5       4   5    3


Subject    Science
Student ID       4
Class
A                3
B                4

In [23]:
df.unstack([0,2])

           Final
Class          A                B
Subject      Art Math Science Art Math Science
Student ID
1              3    4       3   3    3       5
2              3    5       4   5    4       4
3              5    5       3   3    5       4
4              5    3       3   5    3       4

In [24]:
df.unstack([2,0])

           Final
Subject      Art Math Science Art Math Science
Class          A    A       A   B    B       B
Student ID
1              3    4       3   3    3       5
2              3    5       4   5    4       4
3              5    5       3   3    5       4
4              5    3       3   5    3       4

In [25]:
df.unstack([0,1])

           Final
Class          A           B
Student ID     1  2  3  4  1  2  3  4
Subject
Art            3  3  5  5  3  5  3  5
Math           4  5  5  3  3  4  5  3
Science        3  4  3  3  5  4  4  4

In [26]:
df.unstack([1,0])

           Final
Student ID     1  2  3  4  1  2  3  4
Class          A  A  A  A  B  B  B  B
Subject
Art            3  3  5  5  3  5  3  5
Math           4  5  5  3  3  4  5  3
Science        3  4  3  3  5  4  4  4