Chapter 22
# 利用melt() 将宽格式转换为长格式
Book_1《编程不难》 | 鸢尾花书：从加减乘除到机器学习

In [1]:
import pandas as pd

In [2]:
data = {
    'Student ID': ['1', '2', '3', '4'],
    'Art':        [4, 3, 5, 4],
    'Math':       [3, 4, 5, 3],
    'Science':    [5, 4, 3, 4]}

In [8]:
df = pd.DataFrame(data)
df

  Student ID  Art  Math  Science
0          1    4     3        5
1          2    3     4        4
2          3    5     5        3
3          4    4     3        4

In [9]:
df.columns

Index(['Student ID', 'Art', 'Math', 'Science'], dtype='object')

In [6]:
df.columns.names = ['Subject'] #
df

Subject Student ID  Art  Math  Science
0                1    4     3        5
1                2    3     4        4
2                3    5     5        3
3                4    4     3        4

In [7]:
df.columns

Index(['Student ID', 'Art', 'Math', 'Science'], dtype='object', name='Subject')

melt() 需要指定 id_vars 参数，表示保持不变的列，同时还可以选择 value_vars 参数来指
定哪些列需要被转换。

In [10]:
melted_df = df.melt(id_vars='Student ID',
                    var_name='Subject', #将需要转化的列的标签作为subject
                    value_vars=['Art','Math','Science'],
                    value_name='Score')
melted_df

   Student ID  Subject  Score
0           1      Art      4
1           2      Art      3
2           3      Art      5
3           4      Art      4
4           1     Math      3
5           2     Math      4
6           3     Math      5
7           4     Math      3
8           1  Science      5
9           2  Science      4
10          3  Science      3
11          4  Science      4