Chapter 22
# 利用groupby() 汇总学生成绩
Book_1《编程不难》 | 鸢尾花书：从加减乘除到机器学习

In [1]:
import pandas as pd
import numpy as np

In [2]:
# 创建班级、学号和科目的所有可能组合
classes = ['A', 'B']
stu_ids = [1, 2, 3, 4]
subjects = ['Art', 'Math', 'Science']

In [3]:
# 使用随机数生成成绩数据
np.random.seed(0)
length = len(classes ) * len(stu_ids) * len(subjects)
data = np.random.randint(3, 6, size=(length))

In [4]:
# 创建多行标签数据帧
index = pd.MultiIndex.from_product(
    [classes, stu_ids, subjects],
    names=['Class', 'Student ID', 'Subject'])
df = pd.DataFrame(data, index=index, columns=['Score'])
df

                          Score
Class Student ID Subject
A     1          Art          3
                 Math         4
                 Science      3
      2          Art          4
                 Math         4
                 Science      5
      3          Art          3
                 Math         5
                 Science      3
      4          Art          3
                 Math         3
                 Science      5
B     1          Art          4
                 Math         5
                 Science      5
      2          Art          3
                 Math         4
                 Science      4
      3          Art          4
                 Math         4
                 Science      3
      4          Art          4
                 Math         3
                 Science      3

In [5]:
# 1) 每个班级各个科目平均成绩
class_subject_avg = df.groupby(
    ['Class', 'Subject'])['Score'].mean()
class_subject_avg  #选取['Class', 'Subject']为一组

Class  Subject
A      Art        3.25
       Math       4.00
       Science    4.00
B      Art        3.75
       Math       4.00
       Science    3.75
Name: Score, dtype: float64

In [6]:
# 2) 每个班级各个学生的平均成绩
class_student_avg = df.groupby(
    ['Class', 'Student ID'])['Score'].mean()
class_student_avg

Class  Student ID
A      1             3.333333
       2             4.333333
       3             3.666667
       4             3.666667
B      1             4.666667
       2             3.666667
       3             3.666667
       4             3.333333
Name: Score, dtype: float64

In [7]:
# 3) 两个班级放在一起各个科目平均成绩
both_class_avg = df.groupby(
    'Subject')['Score'].mean()
both_class_avg

Subject
Art        3.500
Math       4.000
Science    3.875
Name: Score, dtype: float64

In [8]:
# 4) 两个班级每个同学总成绩，并排名
student_total_score = df.groupby(
    ['Class','Student ID'])['Score'].sum().sort_values(
    ascending=False)
student_total_score # ort_values(ascending=False)降序

Class  Student ID
B      1             14
A      2             13
       4             11
       3             11
B      3             11
       2             11
A      1             10
B      4             10
Name: Score, dtype: int64