Chapter 22
# 利用stack() 将宽格式转换为长格式，选择特定列级别
Book_1《编程不难》 | 鸢尾花书：从加减乘除到机器学习

In [1]:
import pandas as pd

In [2]:
data = {
    ('A', 'Art'):     [4, 3, 5, 4],
    ('A', 'Math'):    [3, 4, 5, 3],
    ('A', 'Science'): [5, 4, 3, 4],
    ('B', 'Art'):     [3, 4, 5, 4],
    ('B', 'Math'):    [4, 5, 3, 3],
    ('B', 'Science'): [5, 3, 4, 5]}
    # ('A', 'Art')二级列索引

In [3]:
# 创建多层行标签数据帧
df = pd.DataFrame(data, index=[1, 2, 3, 4])
df

    A                B
  Art Math Science Art Math Science
1   4    3       5   3    4       5
2   3    4       4   4    5       3
3   5    5       3   5    3       4
4   4    3       4   4    3       5

In [4]:
# 添加行标签名称
df.columns.names = ['Class', 'Subject'] # 使用list多级索引
df.index.names = ['Student ID']
df

Class        A                B
Subject    Art Math Science Art Math Science
Student ID
1            4    3       5   3    4       5
2            3    4       4   4    5       3
3            5    5       3   5    3       4
4            4    3       4   4    3       5

In [5]:
# 选择 'Class' 进行 stack() 操作
stacked_df = df.stack(level='Class') # 指定需要转换的列标签
stacked_df
# stacked_df = df.stack(level=0)

/tmp/ipykernel_1795/1764318447.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_df = df.stack(level='Class') # 指定需要转换的列标签

Subject           Art  Math  Science
Student ID Class
1          A        4     3        5
           B        3     4        5
2          A        3     4        4
           B        4     5        3
3          A        5     5        3
           B        5     3        4
4          A        4     3        4
           B        4     3        5

In [6]:
stacked_df = df.stack(level=[0,1])

/tmp/ipykernel_1795/3851753195.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_df = df.stack(level=[0,1])

In [10]:
stacked_df

Student ID  Class  Subject
1           A      Art        4
                   Math       3
                   Science    5
            B      Art        3
                   Math       4
                   Science    5
2           A      Art        3
                   Math       4
                   Science    4
            B      Art        4
                   Math       5
                   Science    3
3           A      Art        5
                   Math       5
                   Science    3
            B      Art        5
                   Math       3
                   Science    4
4           A      Art        4
                   Math       3
                   Science    4
            B      Art        4
                   Math       3
                   Science    5
dtype: int64

# 修改行列名称
df.columns.names = ['Subject']
df.index.names = ['Student ID']
# 将长格式转化为宽格式
a df.stack().reset_index().rename(columns={0: 'Final'})



---



df = pd.DataFrame(data)
df.columns.names = ['Subject']
melted_df = df.melt(id_vars='Student ID',
 var_name='Subject',
 value_vars=['Art','Math','Science'],
 value_name='Score')

In [12]:
type(stacked_df)

pandas.core.series.Series