Chapter 19
# 从网页下载数据
Book_1《编程不难》 | 鸢尾花书：从加减乘除到机器学习

In [1]:
import pandas as pd
import requests

In [3]:
# 设置数据源的URL
url = 'https://fred.stlouisfed.org/data/SP500.txt'

In [4]:
# 发送GET请求并获取数据
response = requests.get(url)

In [7]:
response

In [16]:

if response.status_code == 200:
    # 先查看前60行，了解数据结构
    lines = response.text.split('\n')
    for i, line in enumerate(lines[40:80]):  # 查看skiprows前后的行
        print(f"Line {i+41}: {line}")

Line 41:     <meta name="apple-itunes-app" content="app-id=451715489">
Line 42:     <meta name="google-play-app" content="app-id=org.stlouisfed.research.fred">
Line 43:
Line 44:
Line 45:
Line 46:         <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
Line 47:
Line 48:     <!--<meta name="viewport" content="width=device-width">-->
Line 49:
Line 50:
Line 51:
Line 52:
Line 53: </head>
Line 54: <body class="">
Line 55:
Line 56: <!-- Google Tag Manager (noscript) -->
Line 57: <noscript>
Line 58:     <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5L322W"
Line 59:             height="0" width="0" style="display:none;visibility:hidden"></iframe>
Line 60: </noscript>
Line 61: <!-- End Google Tag Manager (noscript) -->
Line 62:
Line 63: <!-- pingdom_uptime_check=uXCPjTUzTxL7ULra -->
Line 64: <link rel="stylesheet" type="text/css" href=/assets/bootstrap/dist/css/1783358036.bootstrap.min.css>
Line 65: <link rel="stylesheet" type="text/css" href=/assets/fontawesome-free/css/all.min.css>
Line 66: <script></script>
Line 67: <link rel="stylesheet" type="text/css" href=/css/1783358039.pager.min.css>
Line 68: <script></script>
Line 69: <link rel="stylesheet" type="text/css" href=/assets/select2/dist/css/1783358034.select2.min.css>
Line 70:
Line 71:
Line 72: <link rel="preconnect" href="https://fonts.googleapis.com">
Line 73: <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
Line 74: <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
Line 75: <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap" rel="stylesheet">
Line 76: <!--googleoff: snippet-->
Line 77: <a href="#content-container" class="skip-to">Skip to main content</a>
Line 78: <!--googleon: snippet-->
Line 79: <a id="top"></a>
Line 80: <!--Move content shift styles internal to boost performance scores-->

In [18]:
# 检查是否成功获取数据
if response.status_code == 200:
    # 数据以制表符分隔
    df = pd.read_csv(url,skiprows=44, sep='\t')
else:
    print("Failed to fetch data from the source")

In [19]:
df

     <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
0         <!--<meta name="viewport" content="width=d...
1                                               </head>
2                                       <body class="">
3                <!-- Google Tag Manager (noscript) -->
4                                            <noscript>
...                                                 ...
6192                                          </script>
6193  <link href=/css/1783358039.contact.min.css rel...
6194                                  <script></script>
6195  <script type="text/javascript"  src="/tpzgfsgu...
6196                                            </html>

[6197 rows x 1 columns]

In [20]:
# 检查是否成功获取数据
if response.status_code == 200:
    # 数据以制表符分隔
    df = pd.read_csv(url, skiprows=44, sep=r'\s+',
                 on_bad_lines='skip')  # 跳过问题行
else:
    print("Failed to fetch data from the source")

In [21]:
df

,<meta,"content=""width=device-width,","initial-scale=1.0,","maximum-scale=1.0,","user-scalable=0""","name=""viewport"">"
0,<!--<meta,"name=""viewport""","content=""width=device-width"">-->",NaN,NaN,NaN
1,</head>,NaN,NaN,NaN,NaN,NaN
2,<body,"class="""">",NaN,NaN,NaN,NaN
3,<!--,Google,Tag,Manager,(noscript),-->
4,<noscript>,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
6122,</script>,NaN,NaN,NaN,NaN,NaN
6123,<link,href=/css/1783358039.contact.min.css,"rel=""stylesheet""","media=""(min-width:","767px)"">",NaN
6124,<script></script>,NaN,NaN,NaN,NaN,NaN
6125,<script,"type=""text/javascript""","src=""/tpzgfsgu6wGm7Dr08MNt/Et5cwfSGfSG0NJ5maf/...",NaN,NaN,NaN
6126,</html>,NaN,NaN,NaN,NaN,NaN

In [17]:
# 检查是否成功获取数据
if response.status_code == 200:
    # 数据以制表符分隔
    df = pd.read_csv(url,skiprows=44, sep='\\s+')
else:
    print("Failed to fetch data from the source")

ParserError: Error tokenizing data. C error: Expected 6 fields in line 61, saw 7

In [ ]:
df['DATE'] = pd.to_datetime(df['DATE'])
df.set_index('DATE', inplace=True)

In [ ]:
df.head()

              VALUE
DATE
2013-10-03  1678.66
2013-10-04  1690.50
2013-10-07  1676.12
2013-10-08  1655.45
2013-10-09  1656.40